Log game versions before save conversion
ParadoxGameConverters/ImperatorToCK3 pull request #199
Opened 2021-04-25 22:50 UTC by IhateTrains

![image](https://user-images.githubusercontent.com/29546927/116012175-48316a00-a629-11eb-9ac3-2bafdcf42eda.png)

2021-04-25 23:40 UTC, Idhrendur requested changes
Don't forget to update CMakelists.txt

2021-04-25 23:54 UTC, IhateTrains commented
> Don't forget to update CMakelists.txt

Added include dir ✔️

2021-04-26 00:51 UTC, Idhrendur approved these changes

2021-04-26 06:28 UTC, Zemurin approved these changes

2021-04-26 08:35 UTC, merged