I:R centuries support - Part 1
ParadoxGameConverters/ImperatorToCK3 pull request #251
Opened 2021-07-31 18:43 UTC by IohannesIohannium

(Off-topic, I got myself a working computer.)

- Creates a 150 AD bookmark (currently flagged as unplayable)
- Blocks pilgrimage to pagan faiths that frankly never had a concept of pilgrimage to even begin with
- Adds century scripted triggers

2021-08-01 12:13 UTC, IhateTrains requested changes

2021-08-01 14:24 UTC, IohannesIohannium commented on ImperatorToCK3/Data_Files/blankMod/output/common/scripted_triggers/00_century_triggers.txt
> +	year = 102
Centuries start at ....1; for example, the 21st century started at 2001 and will end at 2100.

2021-08-01 14:24 UTC, IohannesIohannium commented on ImperatorToCK3/Data_Files/blankMod/output/common/scripted_triggers/00_century_triggers.txt
> +	NOT = { year = 202 }
See above

2021-08-01 14:25 UTC, IohannesIohannium commented on ImperatorToCK3/Data_Files/blankMod/output/localization/english/new_eras_l_english.yml
> + culture_era_late_classical_desc:0 "Lacking a better label, Late Classical refers to the period of troubles that saw the Roman Empire reduced to nothing more than a geographical expression. Devoid of
My bad, feel free to suggest a better description

2021-08-01 14:26 UTC, IhateTrains commented on ImperatorToCK3/Data_Files/blankMod/output/common/scripted_triggers/00_century_triggers.txt
> +	year = 102
I know, but don't your conditions contradict that?

2021-08-01 14:31 UTC, IohannesIohannium commented on ImperatorToCK3/Data_Files/blankMod/output/common/decisions/10_religious_decisions.txt
> +			faith = { is_in_family = rf_pagan } # No Pilgrimage in Paganism
Readded pilgrimage for Hellenic and Arab pagans

2021-08-01 14:35 UTC, IohannesIohannium commented on ImperatorToCK3/Data_Files/blankMod/output/localization/ir_welcome_l_english.yml
> + welcome_ok:0 "Ok"
Solved

2021-08-01 15:20 UTC, IohannesIohannium commented on ImperatorToCK3/Data_Files/blankMod/output/common/scripted_triggers/00_century_triggers.txt
> +	year = 102
You're right.

2021-08-04 17:26 UTC, IhateTrains commented
Is the bookmark button supposed to look like this?
![image](https://user-images.githubusercontent.com/29546927/128226469-f09a097a-aea6-4e18-92c2-89036a608e3e.png)

2021-08-04 17:28 UTC, IhateTrains commented
Some errors introduced in the PR:
```
[19:24:31][pdx_assert.cpp:568]: Assertion failed: Creation of dynamic token "1st_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "1st_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "2nd_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "3rd_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "4th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "5th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "6th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "7th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "8th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "9th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "10th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "11th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "12th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "13th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "14th_century" failed, keywords may not start with a digit or '-'.
[19:24:31][lexer.cpp:209]: Creation of dynamic token "15th_century_or_later" failed, keywords may not start with a digit or '-'.
[19:24:47][jomini_trigger.cpp:871]: Inconsistent trigger scopes (faith vs. religion) in file: common/decisions/10_religious_decisions.txt line: 774
```

2021-08-04 20:46 UTC, IohannesIohannium commented
> Is the bookmark button supposed to look like this?
> ![image](https://user-images.githubusercontent.com/29546927/128226469-f09a097a-aea6-4e18-92c2-89036a608e3e.png)

It is how I made it, but anybody who can make it less weird is welcome

2021-08-04 20:47 UTC, IohannesIohannium commented
> Some errors introduced in the PR:
> 
> ```
> [19:24:31][pdx_assert.cpp:568]: Assertion failed: Creation of dynamic token "1st_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "1st_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "2nd_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "3rd_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "4th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "5th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "6th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "7th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "8th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "9th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "10th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "11th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "12th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "13th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "14th_century" failed, keywords may not start with a digit or '-'.
> [19:24:31][lexer.cpp:209]: Creation of dynamic token "15th_century_or_later" failed, keywords may not start with a digit or '-'.
> [19:24:47][jomini_trigger.cpp:871]: Inconsistent trigger scopes (faith vs. religion) in file: common/decisions/10_religious_decisions.txt line: 774
> ```

Solved the dynamic token errors

2021-08-04 21:58 UTC, IhateTrains commented on ImperatorToCK3/Data_Files/blankMod/output/common/decisions/10_religious_decisions.txt
> +			}
I'm still not convinced about the need for the addition, but if it's to be added it needs to be working.
Try
```suggestion
			AND = { # Removing pilgrimage option for pagans who never had such a thing attested
				religion = { is_in_family = rf_pagan }
				NOR = {
					faith = faith:hellenic_pagan
					faith = faith:eleusinian_mysteries
					faith = faith:mithraic_mysteries
					faith = faith:arabic_pagan
				}
			}

```

2021-08-05 22:47 UTC, IhateTrains commented on ImperatorToCK3/Data_Files/blankMod/output/localization/english/new_eras_l_english.yml
> + culture_era_late_classical_desc:0 "Lacking a better label, Late Classical refers to the period of troubles that saw the Roman Empire reduced to nothing more than a geographical expression. Devoid of
This shouldn't hold the PR back, I will just open an issue to improve the desc.

2021-08-05 22:48 UTC, IhateTrains approved these changes
The script error is fixed.

2021-08-05 22:48 UTC, merged