Benelux + Mapping Holes Cover Up
ParadoxGameConverters/ImperatorToCK3 pull request #728
Opened 2022-05-02 19:01 UTC by RaduM84

Benelux + Mapping Holes Cover Up

2022-05-02 19:11 UTC, IhateTrains requested changes

2022-05-02 19:11 UTC, IhateTrains commented on ImperatorToCK3/Data_Files/configurables/province_mappings.txt
> +	link = { imp = 3723 imp = 3701 ck3 = 2694 } # Bingium, Mogontiacum -> MAINZ
Mogontiacum is Mainz
```suggestion
	link = { imp = 3701 imp = 3723 ck3 = 2694 } # Mogontiacum, Bingium -> MAINZ

```

2022-05-02 19:11 UTC, IhateTrains commented on ImperatorToCK3/Data_Files/configurables/province_mappings.txt
> +	link = { imp = 3721 ck3 = 2086 ck3 = 2084 } # Confluentes -> ADENAU, KOBLENZ
```suggestion
	link = { imp = 3721 ck3 = 2084 ck3 = 2086 } # Confluentes -> KOBLENZ, ADENAU

```

2022-05-02 19:11 UTC, IhateTrains commented on ImperatorToCK3/Data_Files/configurables/province_mappings.txt
> +	link = { imp = 3620 } # Obilonna -> DROPPED
Is the dropping intended?

2022-05-02 19:11 UTC, IhateTrains commented on ImperatorToCK3/Data_Files/configurables/province_mappings.txt
> +	link = { imp = 1177 imp = 1193 imp = 1022 imp = 1205 imp = 1195 ck3 = 1924 } # Cauca, Confluentia, Segovia, Carpetana Luga, Miaccum -> SEGOVIA
```suggestion
	link = { imp = 1022 imp = 1177 imp = 1193 imp = 1205 imp = 1195 ck3 = 1924 } # Segovia, Cauca, Confluentia, Carpetana Luga, Miaccum -> SEGOVIA

```

2022-05-02 19:28 UTC, RaduM84 commented on ImperatorToCK3/Data_Files/configurables/province_mappings.txt
> +	link = { imp = 3620 } # Obilonna -> DROPPED
No, that's a mistake.

2022-05-03 15:36 UTC, IhateTrains approved these changes

2022-05-03 15:36 UTC, merged